### ISSUE TITLE
Create Tabular Data Package with information on public registries

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-registries#1]
# Implementation

We want a [Tabular Data Package](http://dataprotocols.org/tabular-data-package/) which is a listing of known public registries of clinical trial data. 

We'll start by adding all those listed on the WHO Clinical Trials Registry Platform [here](http://www.who.int/ictrp/network/primary/en/) and [here](http://www.who.int/ictrp/network/partner/en/)

File structure should be as per normal Tabular Data Package conventions: a top-level `README.md` and `datapackage.json`, and a CSV file of the data under `data/*`
- [x] Create entries for all public registries mentioned on the above links from the WHO website, with the following fields
  - [x] Name
  - [x] URL
  - [x] Address
  - [x] Email
  - [x] License URL
  - [x] Data Access Type (enum: scrape, api, download)
  - [x] Do we need other fields? Add them if yes.

**Comment by danfowler** [comment]
@pwalsh how about a slug field?

**Comment by pwalsh** [comment]
@danfowler yes.
